sudo: required
dist: trusty
language: python
before_install:
  - sudo add-apt-repository -y ppa:streetcrypto7/rocksdb
  - sudo add-apt-repository -y ppa:streetcrypto7/leveldb
  - sudo apt-get -qq update
  - sudo apt-get install -yq libsnappy-dev zlib1g-dev libbz2-dev libgflags-dev liblz4-dev librocksdb-dev libleveldb-dev
python:
  - "3.8-dev"
  - "3.8"
  - "3.7"
  - "nightly"
# command to install dependencies
install:
  - pip install aiohttp
  - pip install aiorpcX
  - pip install plyvel
  - pip install pycodestyle
  - pip install pylru
  - pip install python-rocksdb
  - pip install pytest-asyncio
  - pip install pytest-cov
  - pip install Sphinx
# command to run tests
script:
  - pytest --cov=electrumx
  - pycodestyle --max-line-length=100 electrumx/server/*.py electrumx/lib/*.py *.py
  - sh -c "cd docs && make html"
# Dont report coverage from nightly
after_success:
  - if [[ $(python3 -V 2>&1) == *"Python 3.7"* ]]; then
      pip install python-coveralls;
      coveralls;
    fi
